# Generated by Django 5.2.1 on 2025-05-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DicomStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('dicom_file', models.FileField(upload_to='dicom_files/')),
                ('patient_id', models.CharField(blank=True, max_length=100)),
                ('patient_sex', models.CharField(blank=True, max_length=10)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('study_date', models.DateField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result_left_hip', models.BooleanField(blank=True, null=True)),
                ('result_right_hip', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
